import uuid
from datetime import datetime
from typing import Optional, List, Dict, Any
from sqlalchemy import String, DateTime, Float
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from hybrid_recommendation_server.core.database import Base

class UserRecommendation(Base):
    """
    Cached personalized recommendation list generated by the Hybrid Engine.
    Enables sub-15ms lookups from the main backend.
    """
    __tablename__ = "UserRecommendation"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id: Mapped[str] = mapped_column("userId", String, unique=True, index=True, nullable=False)
    recommendations: Mapped[List[Dict[str, Any]]] = mapped_column("recommendations", JSONB, default=list, nullable=False)
    updated_at: Mapped[datetime] = mapped_column("updatedAt", DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

class CourseBundle(Base):
    """
    Frequent course bundles mined from purchase orders via Apriori.
    """
    __tablename__ = "CourseBundle"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=lambda: str(uuid.uuid4()))
    source_course_id: Mapped[str] = mapped_column("sourceCourseId", String, index=True, nullable=False)
    target_course_id: Mapped[str] = mapped_column("targetCourseId", String, index=True, nullable=False)
    support: Mapped[float] = mapped_column("support", Float, nullable=False)
    confidence: Mapped[float] = mapped_column("confidence", Float, nullable=False)
    lift: Mapped[float] = mapped_column("lift", Float, nullable=False)
    updated_at: Mapped[datetime] = mapped_column("updatedAt", DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
