import React from 'react';
import {
    Bar,
    BarChart,
    CartesianGrid,
    Legend,
    ResponsiveContainer,
    Tooltip,
    XAxis,
    YAxis
} from "recharts";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Skeleton } from '@/components/ui/skeleton';
import { Users, DollarSign, BookOpen } from "lucide-react";
import { useGetCourseAnalyticsQuery } from '@/features/api/adminDataApi';


// --- Skeleton Component for a better loading state ---
const DashboardSkeleton = () => ( 
    <div className="grid gap-6 grid-cols-1 sm:grid-cols-2 lg:grid-cols-4">
        {[...Array(4)].map((_, i) => (
             <Card key={i}><CardHeader><Skeleton className="h-6 w-1/2" /></CardHeader><CardContent><Skeleton className="h-10 w-3/4" /></CardContent></Card>
        ))}
        <Card className="col-span-1 sm:col-span-2 lg:col-span-4"><CardContent className="pt-6"><Skeleton className="h-72 w-full" /></CardContent></Card>
    </div>
);

const Dashboard = () => {
    const { data, isLoading, isError } = useGetCourseAnalyticsQuery();


    console.log("Dashboard data:", data); // Debugging line to check fetched data

    if (isLoading) return <DashboardSkeleton />;
    if (isError) return <div className="text-red-500 text-center py-10">Failed to load dashboard analytics.</div>;

    const analytics = data?.analytics || [];

    // --- Key Metrics ---
    const totalRevenue = analytics.reduce((sum, c) => sum + (c.totalRevenue || 0), 0);
    const totalStudents = analytics.reduce((sum, c) => sum + (c.enrolledCount || 0), 0);
    const totalCourses = analytics.length;
    const totalPurchases = analytics.reduce((sum, c) => sum + (c.purchaseCount || 0), 0);

    return (
        <div className="space-y-6">
            <h1 className="text-3xl font-bold tracking-tight">Platform Analytics Dashboard</h1>
            
            {/* --- Key Metric Cards --- */}
            <div className="grid gap-6 grid-cols-1 sm:grid-cols-2 lg:grid-cols-4">
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Total Revenue</CardTitle>
                        <DollarSign className="h-4 w-4 text-muted-foreground"/>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">Rs{totalRevenue.toLocaleString()}</div>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Total Students</CardTitle>
                        <Users className="h-4 w-4 text-muted-foreground"/>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{totalStudents.toLocaleString()}</div>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Total Courses</CardTitle>
                        <BookOpen className="h-4 w-4 text-muted-foreground"/>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{totalCourses}</div>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Total Purchases</CardTitle>
                        <DollarSign className="h-4 w-4 text-muted-foreground"/>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{totalPurchases}</div>
                    </CardContent>
                </Card>
            </div>
            
            {/* --- Sales Chart Card --- */}
            <Card className="col-span-1 sm:col-span-2 lg:col-span-4">
                <CardHeader>
                    <CardTitle>Revenue by Course</CardTitle>
                    <CardDescription>
                        An overview of revenue generated by each course.
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <ResponsiveContainer width="100%" height={350}>
                        <BarChart data={analytics}>
                            <CartesianGrid strokeDasharray="3 3" />
                            <XAxis dataKey="courseTitle" stroke="#888888" fontSize={12} tickLine={false} axisLine={false} />
                            <YAxis stroke="#888888" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `Rs${value / 1000}k`}/>
                            <Tooltip formatter={(value) => [`Rs${value.toLocaleString()}`]}/>
                            <Legend />
                            <Bar dataKey="totalRevenue" fill="#2563eb" radius={[4, 4, 0, 0]} name="Revenue"/>
                        </BarChart>
                    </ResponsiveContainer>
                </CardContent>
            </Card>
        </div>
    );
};

export default Dashboard;